### ISSUE TITLE
Value from environment

### ISSUE THREAD

**Issue by ptman** [kkyr/fig#1]
Thank you for the library. It is something I've been planning to write myself. But I'd still hope for one more feature. Especially for projects packaged as docker images. Could you support some sort of environment variable interpolation syntax? Like `${FOOBAR}` being read from the environment variable **FOOBAR**?

**Comment by kkyr** [comment]
This is something which I've been considering to add and will get down to when I find some free time (hopefully soon!).

I'm not entirely sure what you mean by you example, where would `${FOOBAR}` be defined, can you please elaborate?

These are my thoughts regarding environment variables. Let's say you have the following struct defined:

```
type Config struct {
   type Server struct {
       Level string `fig:"level"`
   } `fig:"server"`
}
```

You'd be able to set the `Level` field using environment variable `SERVER_LEVEL`. There would be additional options such as adding a prefix to all variables, i.e. `MYAPP_SERVER_LEVEL` and a custom separator i.e. `MYAPP-SERVER-LEVEL`.

Please share your thoughts!

**Comment by ptman** [comment]
E.g. in the config:

```yaml
path: '/srv/projects/${FOOBAR}'
```

Or maybe even in the struct tags, but then they would have to provide the whole value.

**Comment by kkyr** [comment]
I prefer the way I outlined above since it keeps definitions the same, in contrast to your suggestion which introduces additional syntax specific to environment variables. Loading from the environment however should be disabled by default in order to avoid accidental loading of fields, with an option for enabling it.
