### ISSUE TITLE
fig should be more customizable via hooks

### ISSUE THREAD

**Issue by rsj-ioki** [kkyr/fig#10]
fig uses the very powerful mapstructure under the hood just like viper. But unlike [viper](https://github.com/spf13/viper) or [uconfig](https://github.com/omeid/uconfig) it does not expose some sort of hook/middleware mechanism so that user defined logic can be executed as part of loading config

Introducing such a behavior might break backwards compatibility but it would be worth it in the long run.

**Comment by kkyr** [comment]
I'm leaning against this since I'd like to keep fig as a simple configuration library that does few things and does them well. More complex use cases would better be served by more powerful libraries, such as viper.

Nonetheless, I'd be open to at least hearing what use cases you have in mind.
