### ISSUE TITLE
Make TOML / YAML dependency optional, somehow

### ISSUE THREAD

**Issue by Arteneko** [kkyr/fig#2]
The goal would be to avoid the dependency on one of them if a project uses only the other.

**Comment by kkyr** [comment]
Not sure if this is even possible, maybe with submodules? Not a route I'd like to go down though.

You could always fork and remove the decoders you're not using.

**Comment by Arteneko** [comment]
> Not a route I'd like to go down though.

That's fair, I guess it could add a lot of complexity for a niche need.

I wonder about how viper is doing it, since they appear to do so.

I wonder how the compiler could be configured to use x or y adapter for x or y library depending on what's imported.

(That's just my thoughts on the topic)

Still, nice library overall, much simpler than viper!

**Comment by kkyr** [comment]
I guess the way to do it is to define the decoders in submodules and a decoder interface in the fig package. Then clients would have to provide a decoder.

However I'm not convinced it's worth the extra complexity just to get rid of two external dependencies. It's certainly an interesting idea though.

I'll leave the issue open a few more days in case anyone else would like to chip in.

I'm glad you like the library!

**Comment by kkyr** [comment]
Closing as this isn't something that I'm planning to add.
