### ISSUE TITLE
Setting config value to "zero" in file takes default value

### ISSUE THREAD

**Issue by nestor-sk** [kkyr/fig#20]
I really enjoy fig for my configuration, because it is simpler than other solutions, but I found a problem with it that is more than a nuance.

Imagine you have a config value set like below, and then in the config file you want to set it to 0: `log_level: 0`
```
LogLevel    int    `fig:"log_level" default:"1"` // -1:trace 0: debug, 1: info, 2: warn, 3: error, 4: fatal, 5: panic
```

The default value will be used, I assume because at the point it looks if it is set, it thinks it is not because it is set to the "zero" value of the type

**Comment by kkyr** [comment]
Indeed, this is a nuance of how the current logic works and is explained in `doc.go`. You can see a similar issue here: https://github.com/kkyr/fig/issues/13.

There's no easy way around this without significantly changing the core logic, which I'm not against, but I personally don't have time to do so.
