### ISSUE TITLE
validate a values of map

### ISSUE THREAD

**Issue by chaehni** [kkyr/fig#21]
I use fig to initialize a map of structs.
The fields in the struct have a "required" validation tag. However, fig does not enforce this validation.
E.g. 

type Config struct {
	Elements   map[string]Element `fig:"chartConfigs" validate:"required"`
}

type Element struct {
	Name    string `fig:"name" validate:"required"`
}

var cfg Config
fig.Load(&cfg)

**Comment by chaehni** [comment]
Sure. Have a look at this code: https://go.dev/play/p/-_UsOxVklci
I have a `validate:"required"` on the `Name` property. For the third person, the name is missing, yet fig still loads the yaml into the `People` struct without complaining.

**Comment by kkyr** [comment]
Hi @chaehni, this is now fixed on tip. I'll publish a new tag as soon as possible.

While `required` is now working, one thing to note is that `default` does not work [for values defined within a map]. I've updated the documentation to reflect this.

p.s. thanks for flagging this!

**Comment by kkyr** [comment]
Available in [v0.4.0](https://github.com/kkyr/fig/releases/tag/v0.4.0)
